### ISSUE TITLE
Feliz 2021

### ISSUE THREAD

**Issue by adrianoleitedasilva** [onimur/onimur#1]
Murilo, bom dia. 

Primeiramente, feliz 2021. 
Eu conheci o seu perfil por meio de uma Issue que abriram em um repo que tenho chamado Bert Markdown Files(https://github.com/adrianoleitedasilva/best-markdown-files/) e ao ver o seu readme fiquei muito surpreso e até usei como inspiração para alterar o meu readme do perfil.

Estou abrindo essa issue apenas para lhe dar os parabéns e lhe informar que coloquei o seu readme neste repo.

Um forte abraço. 

Até mais.

**Comment by onimur** [comment]
Bom dia, Feliz 2021 também.

Agradeço o comentário e fico muito grato por ter usado ele como inspiração, esse realmente foi o propósito.

**Comment by adrianoleitedasilva** [comment]
Eu curti demais o seu readme meu caro.
